### PR TITLE
Fixes default workspace height

### PR DESCRIPTION
**Pull request by bwalsh**
### New Features
None
### Breaking Changes
None

### Bug Fixes
Ensures height of default workspace

#### before
image

#### after
image

### CODE REVIEW

**Comment by qingyashu** [comment]
Thank you very much @bwalsh  for fixing this!

**Comment by bwalsh** [comment]
@qingyashu you're welcome.  thanks for your support

**Comment by mpingram** [comment]
Hi @bwalsh, thanks again for fixing this! Just wanted to keep you in the loop about how we're going to merge this -- our integration tests currently depend on building a quay image from an internal branch, so I'm going to create a new PR with these changes, run the integration tests, and merge it.

**Comment by mfshao** [comment]
closing since it has already been merged by https://github.com/uc-cdis/data-portal/pull/646

**Pull request closed without merging**
