### PR TITLE
fix(workspace): if cannot open workspace, show error msg

### PR DESCRIPTION
**Pull request by qingyashu**
Fix funny double navigation bar fo workspace

### Bug Fixes
If cannot open workspace, just show "Error opening workspace..."

### CODE REVIEW

**Comment by PlanXCyborg** [comment]
Jenkins Build 3 : time taken 28 min

**Comment by qingyashu** [comment]
Please have a check in my dev env. Here's preview: 
image

**Comment by frickjack** [comment]
would be cool if we could give the user some advice on what to do ... what should they do?
* cry
* contact administrator
* try again in a few minutes
Maybe ask Vivi to give you a PNG or SVG to include with the error too - sad puppy, frustrated dinosaur - that kind of thing ... building on fire?

**Comment by PlanXCyborg** [comment]
Jenkins Build 4 : time taken 27 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 5 : time taken 1 hr 28 min

**Comment by PlanXCyborg** [comment]
Jenkins Build 6 : time taken 22 min

**Comment by qingyashu** [comment]
Tested on Zakir's env and looks good!

**Comment by PlanXCyborg** [comment]
Jenkins Build 7 : time taken 1 hr 18 min

**Comment by qingyashu** [comment]
🤔  I think this page error is because workspace service is not on? or should we change error message to "Workspace service not enabled, please contact administrator for more information."? what do you think~

**Comment by abgeorge7** [comment]
If there's no other details about the error then I think this is fine!

**Comment by PlanXCyborg** [comment]
Jenkins Build 8 : time taken 20 min

**Pull request merged**
