### PR TITLE
Fix/vadc 1417

### PR DESCRIPTION
**Pull request by tianj7**
https://ctds-planx.atlassian.net/browse/VADC-1417

### Improvements
508 coloring change for VA mailing link

Before:
Screenshot 2024-11-14 at 3 22 49 PM

After:
Screenshot 2024-11-14 at 3 20 39 PM

### CODE REVIEW

**Review by m0nhawk — APPROVED** [review]

**Comment by m0nhawk** [comment]
@tianj7 please, use `feat/vadc_sprint22` as base branch for this.

**Comment by tianj7** [comment]
> @tianj7 please, use `feat/vadc_sprint22` as base branch for this.

Unfortunately I merged my previous bug fix for team project into master and I need that bug fix for the link to show up to check the color. This branch has too many file changes from master for sprint branch to be "clean" like Jarvis wants. Will use sprint branch for future 508 tickets.

**Review by m0nhawk — DISMISSED** [review]

**Review by jarvisraymond-uchicago — CHANGES_REQUESTED** [review]
Please run 

```npm run stylelint```
To lint your CSS. 

The current code fails the linter, due to missing space in your CSS here: 
```.team-project-modal a{```

I believe the linter requires: 
```.team-project-modal a {```

**Review by jarvisraymond-uchicago — APPROVED** [review]
Looks good to me.

**Comment by paulineribeyre** [comment]
The bullet points in this PR description are not displaying well in the release notes, please read https://github.com/uc-cdis/cdis-wiki/blob/master/dev/release_notes.md for guidance

**Pull request merged**
